export const projectCardDetails = [
	{
		id: 1,
		title: 'Google DSC Coming Soon',
		image_url: './assets/img/projects/coming-soon.png',
		description: `Coming Soon Page for Google DSC SJEC.`,
		github_link: 'https://github.com/GDSC-SJEC/GDSC-Coming-Soon',
	},
	{
		id: 2,
		title: 'Google DSC Launch Game',
		image_url: './assets/img/projects/launch-game.png',
		description: `Ascend through the trials, and Join the Google DSC SJEC Chapter.`,
		github_link: 'https://github.com/GDSC-SJEC/GSDC-LAUNCH-GAME',
	},
	{
		id: 3,
		title: 'Google DSC FAQ',
		image_url: './assets/img/projects/faq.png',
		description: `The FAQ page to answer the questions and queries of club's member.`,
		github_link: 'https://github.com/GDSC-SJEC/GDSC-SJEC-FAQ',
	},
	{
		id: 4,
		title: 'Google DSC Form',
		image_url: './assets/img/projects/details.png',
		description: `A form page to take in member details.`,
		github_link: 'https://github.com/GDSC-SJEC/GDSC-SJEC-Form',
	},
	{
		id: 5,
		title: 'Discord Bot',
		image_url: './assets/img/projects/discord.png',
		description: `The bot that serves your purpose.`,
		github_link: 'https://github.com/GDSC-SJEC/discord-bot',
	},
	{
		id: 6,
		title: 'Google DSC Website',
		image_url: './assets/img/projects/website.png',
		description: `Website for Google Developer Student Clubs St Joseph Engineering College, Mangalore`,
		github_link: 'https://github.com/GDSC-SJEC/GDSC-Website',
	},
	{
		id: 7,
		title: 'Animedoro',
		image_url: './assets/img/projects/animedoro.jpg',
		description: `Animedoro is a time management technique similar to pomodoro, but with a twist!`,
		github_link: 'https://github.com/GDSC-SJEC/Animedoro',
	},
];
