export const projectCardDetails = [
	{
		id: 1,
		title: 'Delta Landing Page',
		image_url: './assets/img/projects/delta.png',
		description: `Landing page for Delta SJEC.`,
		github_link: 'https://github.com/GDSC-SJEC/Delta-Landing-Page',
	},
	{
		id: 2,
		title: 'Tiara 2022',
		image_url: './assets/img/projects/tiara.png',
		description: `Official Tiara 2022 Website, developed by Delta SJEC.`,
		github_link: 'https://github.com/GDSC-SJEC/Tiara-2022',
	},
	{
		id: 3,
		title: 'TEDxSJEC 2022',
		image_url: './assets/img/projects/tedx.png',
		description: `Official TEDxSJEC 2022 Website, developed by Delta SJEC.`,
		github_link: 'https://github.com/GDSC-SJEC/TEDx',
	},
	{
		id: 4,
		title: 'Google DSC Coming Soon',
		image_url: './assets/img/projects/coming-soon.png',
		description: `Coming Soon Page for Google DSC SJEC.`,
		github_link: 'https://github.com/GDSC-SJEC/GDSC-Coming-Soon',
		site_link: `https://live.gdscsjec.in`,
	},
	{
		id: 5,
		title: 'Google DSC Launch Game',
		image_url: './assets/img/projects/launch-game.png',
		description: `Ascend through the trials, and Join the Google DSC SJEC Chapter.`,
		github_link: 'https://github.com/GDSC-SJEC/GSDC-LAUNCH-GAME',
		game_link: `https://akk-3211.itch.io/gdsc-launch-game2`,
	},
	{
		id: 6,
		title: 'Google DSC FAQ',
		image_url: './assets/img/projects/faq.png',
		description: `The FAQ page to answer the questions and queries of club's member.`,
		github_link: 'https://github.com/GDSC-SJEC/GDSC-SJEC-FAQ',
		site_link: `https://faq.gdscsjec.in`,
	},
	{
		id: 7,
		title: 'Google DSC Form',
		image_url: './assets/img/projects/details.png',
		description: `A form page to take in member details.`,
		github_link: 'https://github.com/GDSC-SJEC/GDSC-SJEC-Form',
		site_link: `https://details.gdscsjec.in`,
	},
	{
		id: 8,
		title: 'Discord Bot',
		image_url: './assets/img/projects/discord.png',
		description: `The bot that serves your purpose.`,
		github_link: 'https://github.com/GDSC-SJEC/discord-bot',
	},
	{
		id: 9,
		title: 'Google DSC Website',
		image_url: './assets/img/projects/website.png',
		description: `Website for Google Developer Student Clubs St Joseph Engineering College, Mangalore`,
		github_link: 'https://github.com/GDSC-SJEC/GDSC-Website',
		site_link: `https://gdscsjec.in`,
	},
	{
		id: 10,
		title: 'Animedoro',
		image_url: './assets/img/projects/animedoro.jpg',
		description: `Animedoro is a time management technique similar to pomodoro, but with a twist!`,
		github_link: 'https://github.com/GDSC-SJEC/Animedoro',
		app_link: `https://drive.google.com/file/d/13WEomH0wvPPFOr1BfjxwqKlnpcli2SpA/view`,
	},
	{
		id: 11,
		title: 'Team eSJEC Racing Website',
		image_url: './assets/img/projects/tesr.png',
		description: `GDSC SJEC developed a website for Team eSJEC Racing Club, a racing club of SJEC.`,
		github_link: 'https://github.com/GDSC-SJEC/tesr-website',
		site_link: `https://www.teamesjecracing.tech/`,
	},
	{
		id: 12,
		title: 'Certifier - GCCP',
		image_url: './assets/img/projects/cloud.png',
		description: `Certifier is a “bulk certificate generator” and is based on an existing project. This project provides an open source certificate generation solution based on the Flask web framework.`,
		github_link: 'https://github.com/GDSC-SJEC/gccp-gdscsjec-certifier',
	},
];
